version: '3.9'

services:

  zoo1:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      - zoo1


#  kafka-producer:
#    image: kafka-producer:latest
#    ports:
#      - 6000:6000
#    build:
#      context: ./kafka-producer
#      dockerfile: Dockerfile
#    container_name: kafka-producer
#    depends_on:
#      - kafka1
#    environment:
#      - spring.kafka.bootstrap-servers=kafka1:19092
#      - spring.kafka.consumer.group-id=test-group-id
#
#  kafka-consumer-one:
#    image: kafka-consumer-one:latest
#    ports:
#      - 6001:6001
#    build:
#      context: ./kafka-consumer-one
#      dockerfile: Dockerfile
#    container_name: kafka-consumer-one
#    depends_on:
#      - kafka1
#    environment:
#      - spring.kafka.bootstrap-servers=kafka1:19092
#      - spring.kafka.consumer.group-id=test-group-id
#
#  kafka-consumer-two:
#    image: kafka-consumer-two:latest
#    ports:
#      - 6002:6002
#    build:
#      context: ./kafka-consumer-two
#      dockerfile: Dockerfile
#    container_name: kafka-consumer-two
#    depends_on:
#      - kafka1
#    environment:
#      - spring.kafka.bootstrap-servers=kafka1:19092
#      - spring.kafka.consumer.group-id=test-group-id
#
#  kafka-consumer-three:
#    image: kafka-consumer-three:latest
#    ports:
#      - 6003:6003
#    build:
#      context: ./kafka-consumer-three
#      dockerfile: Dockerfile
#    container_name: kafka-consumer-three
#    depends_on:
#      - kafka1
#    environment:
#      - spring.kafka.bootstrap-servers=kafka1:19092
#      - spring.kafka.consumer.group-id=test-group-id
